name: Front end test

on: [push, pull_request]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - name: run in subdirectory
        working-directory: ./wowo-app
        run: npm install
      - name: post coverage
        working-directory: ./wowo-app
        uses: paambaati/codeclimate-action@v2.5.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
        with:
          coverageCommand: npm run coverage
          debug: true
